from typing import Protocol, Optional
from user_account import Admin

class IAdminRepository(Protocol):
    def save(self, admin: Admin) -> None: ...
    def find_by_id(self, admin_id: str) -> Optional[Admin]: ...
    def find_all(self) -> list[Admin]: ...
    def delete(self, admin_id: str) -> None: ...