from typing import Protocol, Optional
from notification import Notification

class INotificationRepository(Protocol):
    def save(self, notification: Notification) -> None: ...
    def find_by_id(self, notification_id: str) -> Optional[Notification]: ...
    def find_all(self) -> list[Notification]: ...
    def delete(self, notification_id: str) -> None: ...
